language:
  - c
compiler:
  - gcc
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - juergen@pabel.net
    on_success:
      - change
    on_failure:
      - always
os:
  - linux
env:
  - LANG="en_US.UTF-8"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libgpgme11-dev libgpg-error-dev libpam0g-dev e2fslibs-dev libconfuse-dev libesmtp-dev liblua5.2-dev libplymouth-dev libglib2.0-dev libgtk-3-dev liblightdm-gobject-1-dev
  - sudo add-apt-repository ppa:jpabel/tokentube -y
  - sudo apt-get update -q
  - sudo apt-get install libgcrypt11 libgcrypt11-dev

