branches:
  only:
    - travis-ci
language:
  - c
compiler:
  - gcc
os:
  - linux
env:
  global:
    - secure: "g/8oLsJJMlrDuHIf9mj82n7czozjIweupdZncg3E3eOgR6fPITZkVWlPNz8i7WlTyk0fyv2+/hs6xvFdLrXtkE5Qeh8cS4zFxsPND/M2WswJhY6uI8oSiXgGf5weZrxEWR6Eu18TRLLujuvpyKfBMWRDaawnS77A9Oiv9XVcvm4="
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libgcrypt11-dev libgpgme11-dev libgpg-error-dev libpam0g-dev e2fslibs-dev libconfuse-dev libesmtp-dev liblua5.2-dev libplymouth-dev libglib2.0-dev libgtk-3-dev liblightdm-gobject-1-dev
script:
  - if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then ./configure && make ; fi
notifications:
  email:
    recipients:
      - juergen@pabel.net
    on_success:
      - change
    on_failure:
      - always

addons:
  coverity_scan:
    project:
      name: "juergenpabel/tokentube"
    notification_email: juergen@pabel.net
    branch_pattern: travis-ci
    build_command_prepend: ./configure
    build_command: make
