#!/bin/sh -e

PREREQ="cryptroot"

prereqs()
{
	echo "$PREREQ"
}

case $1 in
prereqs)
	prereqs
	exit 0
	;;
esac

. /usr/share/initramfs-tools/hook-functions

/usr/sbin/tokentube pba-install -T initramfs -P ${DESTDIR}

echo '#!/bin/sh'                                     > ${DESTDIR}/lib/cryptsetup/scripts/tokentube.fallback
echo 'exec plymouth ask-for-password --prompt "$1"' >> ${DESTDIR}/lib/cryptsetup/scripts/tokentube.fallback
chmod +x  ${DESTDIR}/lib/cryptsetup/scripts/tokentube.fallback

